language: cpp
dist: trusty
sudo: false
#cache: ccache

env:
  global: BUILD_TYPE=Debug
compiler: gcc

matrix:
  include:
    - stage: wheels
      os: osx
      compiler: clang
      script:
        - pip install https://github.com/tgarc/cibuildwheel/archive/revert_pr9.zip
        - CIBW_SKIP="cp26-*" cibuildwheel
      deploy:
        provider: releases
        api_key:
          secure: a/odACohfUh1T00U/v2T9TCiY4KRfgUwBsFJHf1mzmaphZIPwY8lLgYC1HvV7FD+ijrV9FQVxh+u5A+JbHlDSioW5LE5WXaB4KOYUphcCgoy47/FbyxJpQWNy62segip6/RDvKhpgHCc0Ii8qgXBSLtjyoiCRxbXyfX2u5EbD5fkU5Wip4o7Mqk2cp5NEXWx/u76SvOHH+zhueM2MkP4HvPSMI20jFs1vxb4VNK1EE++GdcZq3mwWFAJyPkuMVKxSF430Svm/qkE33btFQpdtAkUdh0jVu+tBD3RBOHvPAKab4uvDU2Pl5WFl+LYwyYKoZYQAIKVhGrwMbb5LlAaR0sfhq4YqT8HMqPBUPEOMo6OQ3zBoQER7QzHPQRFJBPptNMLtc3ugo0YdDc7bHlocDCah2TErlrzEzNxiC0vFCYv+hVSllWtQwMf56s/6LTQVxgska63tqUWbfA6M4yV37s9wJQsyrdlKnepJWdDDm1WxrZ0nhwxMN/tR+TmYi+tnDkY+JxPwBXyibg/ZARn+7spdjrKbE3uKFwQG2OqkJXiW3LOc7VDyK/s5mj1qJmHDTjTOlwyw5BDclkHAF3hvnci7BefkRRKpba01neFmoMHhdidhvvwLCxhEPTgGKW0rwUfMPJpElWJkjI1OmCpwyyEeOP0IOIZKmvdajsINJY=
        file_glob: true
        file: wheelhouse/*
        skip_cleanup: true
        on:
          repo: YannickJadoul/Parselmouth
          tags: true

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      if [ -n "$GCC" ]; then
        CC=gcc-$GCC
        CXX=g++-$GCC
      elif [ -n "$CLANG" ]; then
        CC="ccache clang-$CLANG"
        CXX="ccache clang++-$CLANG"
        export CFLAGS="-Qunused-arguments"
        export CXXFLAGS="-Qunused-arguments -stdlib=libc++"
      fi
      PYTHON_CMD=python$PYTHON
    elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
      #brew install ccache
      #export PATH=/usr/local/opt/ccache/libexec:$PATH
      if [ "$PYTHON" == "3" ]; then
        brew update
        brew install python3
        PYTHON_CMD=python3
      else
        PYTHON_CMD=python
      fi
      CC=clang
      CXX=clang++
    fi

script:
  - mkdir build && cd build && cmake -DPYBIND11_PYTHON_VERSION=$PYTHON -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make install -j 2
  - cd ../installed && $PYTHON_CMD -c "import parselmouth"